name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - prod
  
jobs:

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BACKEND_BUCKET: ${{ secrets.BACKEND_BUCKET }}
          BACKEND_DYNAMO_TABLE: ${{ secrets.BACKEND_DYNAMO_TABLE }}
        run: |
          pushd ${{ github.workspace }}/aws
          terraform init \
            -backend-config="bucket=$BACKEND_BUCKET" \
            -backend-config="key=terraform-state/${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="dynamodb_table=$BACKEND_DYNAMO_TABLE"
          popd

      - name: Select Terraform Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pushd ${{ github.workspace }}/aws
          terraform plan -out ${{ inputs.environment }}.tfplan -var="environment=${{ inputs.environment }}"
          popd

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ github.workspace }}/aws/${{ inputs.environment }}.tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev
    needs: plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ github.workspace }}/artifacts

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BACKEND_BUCKET: ${{ secrets.BACKEND_BUCKET }}
          BACKEND_DYNAMO_TABLE: ${{ secrets.BACKEND_DYNAMO_TABLE }}
        run: |
          pushd ${{ github.workspace }}/aws
          terraform init \
            -backend-config="bucket=$BACKEND_BUCKET" \
            -backend-config="key=terraform-state/${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="dynamodb_table=$BACKEND_DYNAMO_TABLE"
          popd

      - name: Select Terraform Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pushd ${{ github.workspace }}/aws
          terraform apply ${{ github.workspace }}/artifacts/${{ inputs.environment }}.tfplan 
          popd